<?php
$query = " 
CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block` (
  `id_loffc_block` int(11) NOT NULL AUTO_INCREMENT,
  `width` float(10,2) NOT NULL,
  `show_title` tinyint(1) NOT NULL,
  `id_position` tinyint(2) NOT NULL,
  PRIMARY KEY (`id_loffc_block`)
) ENGINE=_MYSQL_ENGINE_  DEFAULT CHARSET=utf8 AUTO_INCREMENT=57 ;

INSERT INTO `_DB_PREFIX_loffc_block` (`id_loffc_block`, `width`, `show_title`, `id_position`) VALUES
(1, 0.00, 0, 1),
(55, 0.00, 1, 2),
(54, 0.00, 1, 2),
(46, 29.00, 1, 2),
(56, 0.00, 1, 2);

CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_item` (
  `id_loffc_block_item` int(11) NOT NULL AUTO_INCREMENT,
  `id_loffc_block` int(11) NOT NULL,
  `type` varchar(25) NOT NULL,
  `link` varchar(2000) NOT NULL,
  `linktype` varchar(25) NOT NULL,
  `link_content` varchar(2000) NOT NULL,
  `module_name` varchar(100) NOT NULL,
  `hook_name` varchar(100) NOT NULL,
  `latitude` varchar(25) NOT NULL,
  `longitude` varchar(25) NOT NULL,
  `addthis` tinyint(1) NOT NULL,
  `show_title` tinyint(1) NOT NULL DEFAULT '1',
  `target` varchar(20) NOT NULL DEFAULT '_self',
  `position` int(11) NOT NULL,
  PRIMARY KEY (`id_loffc_block_item`)
) ENGINE=_MYSQL_ENGINE_  DEFAULT CHARSET=utf8 AUTO_INCREMENT=85 ;

INSERT INTO `_DB_PREFIX_loffc_block_item` (`id_loffc_block_item`, `id_loffc_block`, `type`, `link`, `linktype`, `link_content`, `module_name`, `hook_name`, `latitude`, `longitude`, `addthis`, `show_title`, `target`, `position`) VALUES
(76, 54, 'link', '', 'link', 'my-account.php', '', '', '', '', 0, 1, '_self', 4),
(5, 1, 'custom_html', '', '', '', '', '', '', '', 0, 1, '', 0),
(82, 56, 'link', '', 'link', 'best-sales.php', '', '', '', '', 0, 1, '_self', 0),
(73, 54, 'link', '', 'cms', '4', '', '', '', '', 0, 1, '_self', 1),
(74, 54, 'link', '', 'cms', '3', '', '', '', '', 0, 1, '_self', 2),
(75, 54, 'link', '', 'cms', '3', '', '', '', '', 0, 1, '_self', 3),
(72, 54, 'link', '', 'cms', '1', '', '', '', '', 0, 1, '_blank', 0),
(49, 46, 'custom_html', '', '', '', '', '', '', '', 0, 0, '', 0),
(83, 56, 'link', '', 'link', 'new-products.php', '', '', '', '', 0, 1, '_self', 2),
(77, 55, 'link', '', 'link', 'contact-form.php', '', '', '', '', 0, 1, '_self', 0),
(78, 55, 'link', '', 'link', 'discount.php', '', '', '', '', 0, 1, '_self', 1),
(79, 55, 'link', '', 'cms', '1', '', '', '', '', 0, 1, '_self', 2),
(80, 55, 'link', '', 'link', 'manufacturer.php', '', '', '', '', 0, 1, '_self', 3),
(81, 56, 'link', '', 'link', 'supplier.php', '', '', '', '', 0, 1, '_self', 1),
(84, 56, 'link', '', 'link', 'http://landofcoder.com/demo/prestashop14x/', '', '', '', '', 0, 1, '_self', 3);

CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_item_lang` (
  `id_loffc_block_item` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `text` text NOT NULL,
  PRIMARY KEY (`id_loffc_block_item`,`id_lang`)
) ENGINE=_MYSQL_ENGINE_ DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_loffc_block_item_lang` (`id_loffc_block_item`, `id_lang`, `title`, `text`) VALUES
(78, 4, 'Discount', ''),
(78, 5, 'Discount', ''),
(78, 6, 'Discount', ''),
(79, 1, 'Delivery', ''),
(79, 2, 'Delivery', ''),
(79, 3, 'Delivery', ''),
(79, 4, 'Delivery', ''),
(79, 5, 'Delivery', ''),
(79, 6, 'Delivery', ''),
(5, 1, 'Social Links', '<ul>\r\n<li class=\"twitter\"><a href=\"#\">Follow UsTwitter</a></li>\r\n<li class=\"rss\"><a href=\"#\">rss</a></li>\r\n<li class=\"facebook\"><a href=\"#\">Facebook</a></li>\r\n<li class=\"skype\"><a href=\"#\">Skype</a></li>\r\n<li class=\"linkedin\"><a href=\"#\">Linkedin</a></li>\r\n</ul>'),
(5, 2, 'item 3', '<p>Social Links Follow UsTwitter rss Facebook Skype Linkedin</p>'),
(5, 3, 'item 3', '<p>Social Links Follow UsTwitter rss Facebook Skype Linkedin</p>'),
(5, 4, 'item 3', '<p>Social Links Follow UsTwitter rss Facebook Skype Linkedin</p>'),
(5, 5, 'item 3', '<p>Social Links Follow UsTwitter rss Facebook Skype Linkedin</p>'),
(5, 6, 'item 3', '<p>Social Links Follow UsTwitter rss Facebook Skype Linkedin</p>'),
(0, 1, 'item 1', ''),
(0, 2, 'item 1', ''),
(0, 3, 'item 1', ''),
(0, 4, 'item 1', ''),
(0, 5, 'item 1', ''),
(0, 6, 'item 1', ''),
(80, 3, 'Manufactures', ''),
(80, 4, 'Manufactures', ''),
(80, 5, 'Manufactures', ''),
(80, 1, 'Manufactures', ''),
(80, 2, 'Manufactures', ''),
(77, 5, 'Contact', ''),
(77, 6, 'Contact', ''),
(78, 1, 'Discount', ''),
(78, 2, 'Discount', ''),
(78, 3, 'Discount', ''),
(77, 4, 'Contact', ''),
(75, 3, 'Privacy Policy', ''),
(75, 4, 'Privacy Policy', ''),
(75, 5, 'Privacy Policy', ''),
(75, 6, 'Privacy Policy', ''),
(76, 1, 'Your account', ''),
(76, 2, 'Your account', ''),
(76, 3, 'Your account', ''),
(76, 4, 'Your account', ''),
(76, 5, 'Your account', ''),
(49, 5, 'About us', ''),
(49, 6, 'About us', ''),
(76, 6, 'Your account', ''),
(77, 1, 'Contact', ''),
(77, 2, 'Contact', ''),
(77, 3, 'Contact', ''),
(49, 4, 'About us', ''),
(49, 3, 'About us', ''),
(49, 2, 'About us', ''),
(80, 6, 'Manufactures', ''),
(81, 1, 'Supplier', ''),
(81, 2, 'Supplier', ''),
(81, 3, 'Supplier', ''),
(81, 4, 'Supplier', ''),
(81, 5, 'Supplier', ''),
(49, 1, 'About us', '<div class=\"custom-content\"><img style=\"float: left;\" src=\"http://localhost/lofworks/prestashop_1.4.6.2.custom.1/img/cms/img-aboutus.png\" alt=\"\" width=\"60\" height=\"55\" />\r\n<p>Vestibulum sit amet pretium Aenean ut quam justo varius nulla. Ut risuse</p>\r\n<p>Lorem doloramet consectetur adipiscing pretium nibh.</p>\r\n</div>'),
(72, 1, 'Terms', ''),
(72, 2, 'Terms', ''),
(72, 3, 'Terms', ''),
(72, 4, 'Terms', ''),
(72, 5, 'Terms', ''),
(72, 6, 'Terms', ''),
(73, 1, 'About us', ''),
(73, 2, 'About us', ''),
(73, 3, 'About us', ''),
(73, 4, 'About us', ''),
(73, 5, 'About us', ''),
(73, 6, 'About us', ''),
(74, 1, 'Address', ''),
(74, 2, 'Address', ''),
(74, 3, 'Address', ''),
(74, 4, 'Address', ''),
(74, 5, 'Address', ''),
(74, 6, 'Address', ''),
(75, 1, 'Privacy Policy', ''),
(75, 2, 'Privacy Policy', ''),
(82, 2, 'Top seller', ''),
(82, 1, 'Top seller', ''),
(81, 6, 'Supplier', ''),
(84, 6, 'Phone: (84) 123 456 789', ''),
(84, 5, 'Phone: (84) 123 456 789', ''),
(84, 4, 'Phone: (84) 123 456 789', ''),
(84, 3, 'Phone: (84) 123 456 789', ''),
(84, 2, 'Phone: (84) 123 456 789', ''),
(84, 1, 'Phone: (84) 123 456 789', ''),
(83, 6, 'New product', ''),
(83, 5, 'New product', ''),
(83, 4, 'New product', ''),
(83, 3, 'New product', ''),
(83, 2, 'New product', ''),
(83, 1, 'New product', ''),
(82, 6, 'Top seller', ''),
(82, 5, 'Top seller', ''),
(82, 4, 'Top seller', ''),
(82, 3, 'Top seller', '');

CREATE TABLE IF NOT EXISTS `_DB_PREFIX_loffc_block_lang` (
  `id_loffc_block` int(11) NOT NULL,
  `id_lang` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  PRIMARY KEY (`id_loffc_block`,`id_lang`)
) ENGINE=_MYSQL_ENGINE_ DEFAULT CHARSET=utf8;

INSERT INTO `_DB_PREFIX_loffc_block_lang` (`id_loffc_block`, `id_lang`, `title`) VALUES
(1, 1, 'block 1 haha'),
(1, 2, 'block 1'),
(1, 3, 'block 1 span'),
(1, 4, 'block 1'),
(1, 5, 'block 1'),
(1, 6, 'block 1'),
(55, 6, 'About Dropship'),
(55, 5, 'About Dropship'),
(55, 4, 'About Dropship'),
(54, 4, 'My Account'),
(54, 3, 'My Account'),
(54, 2, 'My Account'),
(54, 1, 'My Account'),
(55, 3, 'About Dropship'),
(55, 2, 'About Dropship'),
(55, 1, 'About Dropship'),
(54, 6, 'My Account'),
(54, 5, 'My Account'),
(46, 6, 'block 3'),
(46, 5, 'block 3'),
(46, 4, 'block 3'),
(46, 3, 'block 3'),
(46, 1, 'About us'),
(46, 2, 'block 3'),
(56, 4, 'Infomation'),
(56, 5, 'Infomation'),
(56, 6, 'Infomation'),
(56, 3, 'Infomation'),
(56, 1, 'Infomation'),
(56, 2, 'Infomation');

";
?>