<?php /* Smarty version Smarty-3.1.19, created on 2015-04-29 08:05:07
         compiled from "/home1/lamppp/htdocs/Simon-theme/admin/themes/default/css/overrides.css" */ ?>
<?php /*%%SmartyHeaderCode:517621655407493b4bd25-07485448%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '77f5cff7de5caf6a3a13433de7a43ee56fe1dd30' => 
    array (
      0 => '/home1/lamppp/htdocs/Simon-theme/admin/themes/default/css/overrides.css',
      1 => 1425623960,
      2 => 'file',
    ),
  ),
  'nocache_hash' => '517621655407493b4bd25-07485448',
  'function' => 
  array (
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.19',
  'unifunc' => 'content_55407493bbb894_33889962',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_55407493bbb894_33889962')) {function content_55407493bbb894_33889962($_smarty_tpl) {?>/* This stylesheet should be used to add your custom styles to the back-office without using the Sass sources. It will be loaded after all the default styles. 
You should NOT edit any other exisiting back-office CSS file manually: they are generated by the Sass preprocessor: http://www.sass-lang.com/ . */<?php }} ?>
